services:
  api-sp4:
    container_name: api-sp4
    image: sp4_entrega
    build: .
    ports:
      - 3000:3000
    depends_on:
      db-sp4:
        condition: service_healthy
    environment:
      - DB_USER=pedro
      - DB_PASSWORD=0907
      - DB_HOST=db-sp4
      - DB_PORT=5432
      - DB=defaultdb

  db-sp4:
    container_name: db-sp4
    image: postgres:12
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=pedro
      - POSTGRES_PASSWORD=0907
      - POSTGRES_DB=defaultdb
    healthcheck:
      test: psql -U pedro defaultdb || exit 1
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1m
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
